# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Bio
    url: /
    weight: 1
  - name: Blog Posts
    url: post/
    weight: 2
  - name: Research Papers
    url: /#papers
    weight: 3
  - name: Work Experience
    url: experience/
    weight: 4
  - name: Projects
    url: projects/
    weight: 5
  - name: Talks
    url: talks/
    weight: 6
